version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on 'date'
      - echo Building java
      - cd Subscription-Microservice
      - mvn compile
      - mvn package
      - echo Building the Docker image...
      - docker build -t service/pod1subscriptionservice .
      - docker tag service/pod1subscriptionservice $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/pod1subscriptionregistry:sub-service
  post_build:
    commands:
      - echo Build completed on 'date'
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/pod1subscriptionregistry:sub-service
      - echo Writing definitions file
      - printf '[{"name":"subs-pod1-container","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/pod1subscriptionregistry:sub-service >taskdefinition.json

artifacts:
  files: Subscription-Microservice/taskdefinition.json